#spring.datasource.url = jdbc:mysql://localhost:3306/shopingmania
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=Colea4895
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/slavici?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1205
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update